name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Docker
        if: ${{ github.repository == 'BC-SECURITY/Empire' }}
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: bcsecurity/empire
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_names: true